spring.application.name=processor

logging.level.org.springframework.r2dbc=TRACE
logging.level.web=DEBUG
logging.level.org.springframework.data=TRACE
logging.level.org.mrpaulwoods.processor=DEBUG

# spring.sql.init.data-locations=classpath:sql/data.sql

#spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.url=r2dbc:postgresql://192.168.1.128:5432/processor
spring.r2dbc.username=postgres
spring.r2dbc.password=hyundai
spring.sql.init.mode=always
